export { GET_ESTADOS,GET_REPORTE_CITAS,VALIDAR_CITA,GET_CITA,GET_REPORTE_X_TRAMITE } from './citas.gql';
export { GET_ROLES,GET_USUARIOS,USER } from './user.gql';
export { GET_NOTIFICACIONES } from './notificacion.gql';

export { GET_RECOMENDACIONES_GENERAL,GET_RECOMENDACIONES,GET_TRAMITES_GENERAL,GET_TOPE,GET_FECHAS,GET_HORAS,UNION_TRAMITE,GET_TRAMITES,GET_DIAS_BLOQ,GET_DAYS_SPECIAL } from './tramites.gql';
